target 'circolapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Inhibit warnings for all pods
  inhibit_all_warnings!
  platform :ios, '13.0'
  # Pods for iosApp
  pod 'shared', :path => '../../shared'
  pod 'Firebase/Messaging'
  pod 'AppStorage', '~> 1.0.3'
  pod "SwiftUIRefresh"
  pod 'Carte'

  post_install do |installer|
    pods_dir = File.dirname(installer.pods_project.path)
    at_exit { `ruby #{pods_dir}/Carte/Sources/Carte/carte.rb configure` }
  end
end
